"""Generate core/corpus_traces.zig from the TASK-008 corpus.

Emits the scripted per-tick key lists (and the meta each trace was recorded
with) for the Phase 1 corpus traces whose mechanic exercises water, ice,
spring tiles or jumping — the set TASK-011.02's differential replays — as a
plain Zig constant core/steer_difftest.zig @embedFile()s. The checksum
fields in the .jsonl files are deliberately not transcribed: they stay the
whole-pipeline oracle, while the differential works on world state.

Run from the repo root (or via core/build.zig, which wires this as a
code-generation step so a corpus edit refreshes the embed automatically):

    python3 core/c_ref/gen_corpus_traces.py
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CORPUS = ROOT / "tests" / "corpus"
OUT = ROOT / "core" / "corpus_traces.zig"

# The traces named by TASK-011.02 AC#1: the four whose meta.json mechanic
# is jump/water/ice/spring gameplay (and whose headless_ai_mask is 0, so
# steer_players sees scripted actions only, exactly as recorded).
SELECTED = [
    "01-single-player-basic",
    "06-water-immersion",
    "07-spring-bounce",
    "08-ice-slide",
    "10-spring-water-mix",
]

HEADER = '''// Generated by core/c_ref/gen_corpus_traces.py from tests/corpus — do not
// edit by hand. One entry per TASK-011.02 trace: the corpus name, its meta
// (seed / headless_players / headless_ai_mask; all four recorded mask 0),
// and the scripted per-tick key lists from the trace's .jsonl, in line
// order. The .jsonl checksum fields stay in the corpus — this file feeds
// the per-subsystem differential, not the end-to-end checksum replay.

// Data-only: the Entry/Trace types are declared at the bottom of this
// generated file (the consumer, core/steer_difftest.zig, @embedFile()s this
// file as a Zig module and reaches them through the import).
pub const traces = [_]@This().Entry{
'''


TYPE_DECLS = """pub const Trace = struct {
    name: []const u8,
    players: usize,
    ai_mask: usize,
    ticks: []const []const []const u8,
};

pub const Entry = struct {
    seed: c_int,
    trace: Trace,
};
"""

def main() -> None:
    entries = []
    for name in SELECTED:
        try:
            meta = json.loads((CORPUS / f"{name}.meta.json").read_text())
        except (OSError, json.JSONDecodeError) as exc:
            sys.exit(f"{name}.meta.json: {exc}")
        ticks = []
        try:
            with (CORPUS / f"{name}.jsonl").open() as f:
                for lineno, line in enumerate(f, 1):
                    try:
                        row = json.loads(line)
                        ticks.append(row["keys"])
                    except (json.JSONDecodeError, KeyError) as exc:
                        sys.exit(f"{name}.jsonl:{lineno}: {exc}")
        except OSError as exc:
            sys.exit(f"{name}.jsonl: {exc}")
        if meta["headless_ai_mask"] != 0:
            sys.exit(f"{name}: expected headless_ai_mask 0 for the TASK-011.02 set")
        entries.append((name, meta, ticks))

    with OUT.open("w") as out:
        out.write(HEADER)
        for name, meta, ticks in entries:
            out.write(f"    .{{ .seed = {meta['seed']}, .trace = .{{\n")
            out.write(f"        .name = {json.dumps(name)},\n")
            out.write(f"        .players = {meta['headless_players']},\n")
            out.write(f"        .ai_mask = {meta['headless_ai_mask']},\n")
            out.write("        .ticks = &.{\n")
            for keys in ticks:
                listed = ", ".join(json.dumps(k) for k in keys)
                out.write(f"            &.{{{listed}}},\n")
            out.write("        },\n    } },\n")
        out.write("};\n\n")
        out.write(TYPE_DECLS)
    total = sum(len(t) for _, _, t in entries)
    print(f"{OUT.name}: {len(entries)} traces, {total} ticks")


if __name__ == "__main__":
    main()
