"""Generate core/collision_corpus_traces.zig from the TASK-008 corpus.

Emits the scripted per-tick key lists (and the meta each trace was recorded
with) for the Phase 1 corpus traces that exercise player bumps and kills —
02-two-player-manual (two players scripted into each other, AI off),
03-two-player-ai-kill / 04-two-player-ai-kill-nogore (CPU bump-kill, gore
on/off) and 05-four-players-ai (full roster, concurrent bump-kills) — as a
plain Zig constant core/collision_difftest.zig imports. The other
multi-player traces (06-water-immersion, 07-spring-bounce,
10-spring-water-mix) keep their second player parked far from the first and
never reach the collision path, so they stay in TASK-011.02's physics set.
The checksum fields in the .jsonl files are deliberately not transcribed:
they stay the whole-pipeline oracle, while the differential works on world
state.

Unlike TASK-011.02's generator, the traces here keep their recorded
headless_ai_mask (the AI-driven traces are exactly the ones that produce
kills), and no_gore is lifted from the meta's extra_flags so the replay
sets main_info.no_gore the way the recording ran.

Run from the repo root (or via core/build.zig, which wires this as a
code-generation step so a corpus edit refreshes the embed automatically):

    python3 core/c_ref/gen_collision_traces.py
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CORPUS = ROOT / "tests" / "corpus"
OUT = ROOT / "core" / "collision_corpus_traces.zig"

HEADER = '''// Generated by core/c_ref/gen_collision_traces.py from tests/corpus — do
// edit by hand. One entry per TASK-011.03 trace: the corpus name, its meta
// (seed / headless_players / headless_ai_mask / no_gore), and the scripted
// per-tick key lists from the trace's .jsonl, in line order. The .jsonl
// checksum fields stay in the corpus — this file feeds the per-subsystem
// differential, not the end-to-end checksum replay.

// Data-only: the Entry/Trace types are declared at the bottom of this
// generated file (the consumer, core/collision_difftest.zig, reaches them
// through the import).
pub const traces = [_]@This().Entry{
'''


TYPE_DECLS = """pub const Trace = struct {
    name: []const u8,
    players: usize,
    ai_mask: usize,
    no_gore: bool,
    expect_kills: bool,
    ticks: []const []const []const u8,
};

pub const Entry = struct {
    seed: c_int,
    trace: Trace,
};
"""


# The traces named by TASK-011.03 AC#1: the multi-player traces whose
# mechanic is two or more bunnies reaching each other — scripted approach,
# CPU bump-kills (gore on and off), and the full four-player roster.
SELECTED = [
    "02-two-player-manual",
    "03-two-player-ai-kill",
    "04-two-player-ai-kill-nogore",
    "05-four-players-ai",
]


def main() -> None:
    entries = []
    for name in SELECTED:
        try:
            meta = json.loads((CORPUS / f"{name}.meta.json").read_text())
        except (OSError, json.JSONDecodeError) as exc:
            sys.exit(f"{name}.meta.json: {exc}")
        if meta["headless_players"] < 2:
            sys.exit(f"{name}: expected more than one headless player")
        ticks = []
        try:
            with (CORPUS / f"{name}.jsonl").open() as f:
                for lineno, line in enumerate(f, 1):
                    try:
                        row = json.loads(line)
                        ticks.append(row["keys"])
                    except (json.JSONDecodeError, KeyError) as exc:
                        sys.exit(f"{name}.jsonl:{lineno}: {exc}")
        except OSError as exc:
            sys.exit(f"{name}.jsonl: {exc}")
        no_gore = "nogore" in "".join(meta.get("extra_flags", []))
        expect_kills = "kill" in meta.get("mechanic", "").lower()
        entries.append((name, meta, ticks, no_gore, expect_kills))

    if len(entries) < 4:
        sys.exit(f"expected the four multi-player corpus traces, found {len(entries)}")

    with OUT.open("w") as out:
        out.write(HEADER)
        for name, meta, ticks, no_gore, expect_kills in entries:
            out.write(f"    .{{ .seed = {meta['seed']}, .trace = .{{\n")
            out.write(f"        .name = {json.dumps(name)},\n")
            out.write(f"        .players = {meta['headless_players']},\n")
            out.write(f"        .ai_mask = {meta['headless_ai_mask']},\n")
            out.write(f"        .no_gore = {'true' if no_gore else 'false'},\n")
            out.write(f"        .expect_kills = {'true' if expect_kills else 'false'},\n")
            out.write("        .ticks = &.{\n")
            for keys in ticks:
                listed = ", ".join(json.dumps(k) for k in keys)
                out.write(f"            &.{{{listed}}},\n")
            out.write("        },\n    } },\n")
        out.write("};\n\n")
        out.write(TYPE_DECLS)
    total = sum(len(t) for _, _, t, _, _ in entries)
    print(f"{OUT.name}: {len(entries)} traces, {total} ticks")


if __name__ == "__main__":
    main()
